import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import {DivColumn,ImageCircular,H1Center,DivRow, DivProjects, DivRRSS, DivRS, Nav,ImageContainer,ImageContainerProjects, ImageStyled, ButtonRs} from '../components/componentsStyled.js'
import locc from '../components/loc.js'
import pokedex from '../components/pokedex.js'
import openair from '../components/openair.js'
import { AccessAlarm, ThreeDRotation } from '@mui/icons-material';
import AddCardIcon from '@mui/icons-material/AddCard';
import { Button } from '@mui/material'










const Proyectos = () =>{
  return ( 
    <DivProjects>
           <h1>League of Counters</h1>
           <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
           </p>
              <ImageStyled
                alt=''
                src={'https://pbs.twimg.com/media/Ex-d7bmWUAgMCUx?format=jpg&name=large'}
                width={600}
                height={500}
              />
              
            
              
      </DivProjects>
    
  )
}




export default function Home() {
  const [contenidoProyectos, setContenidoProyectos] = useState(Proyectos);

  return (
    <>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
     
        <Nav><h1>&quot;<em>Si yo no lo hago nadie lo hara</em>&quot;</h1></Nav>
        <ImageContainer>
            <ImageStyled
              alt=''
              src={'https://pbs.twimg.com/media/Ex-d7bmWUAgMCUx?format=jpg&name=large'}
              width={800}
              height={250}
            />
        </ImageContainer>
        
        <DivColumn>
        <h1>Sobre mi</h1>
        <p>Soy un entusiasta del desarrollo web y estoy siempre buscando nuevas tecnologías y herramientas para seguir mejorando mis habilidades. Me apasiona trabajar en este campo y busco oportunidades para desarrollarme profesionalmente y aplicar mis habilidades en cada proyecto en el que participe. Tengo una actitud positiva y colaborativa en el trabajo en equipo y me esfuerzo por ser meticuloso y preciso en cada tarea que realizo. Mi objetivo es continuar adquiriendo experiencia y conocimiento en el campo del desarrollo web para seguir creciendo personal y profesionalmente.
        </p>
        </DivColumn>
        <DivRRSS >
          <DivRS>
        <ImageContainer>
            <ImageCircular
              alt=''
              src={'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'}
              width={100}
              height={100}
            />
           
        </ImageContainer>
        <Button style={{color:'white'}} href="https://www.linkedin.com/in/gabriel-figueroa-42776b262/"><h1>Github</h1></Button>
            
          </DivRS>
      <DivRS >
          <ImageContainer>
            <ImageCircular
              alt=''
              src={'https://pbs.twimg.com/profile_images/1508518003184349187/1KQYoqPY_400x400.png'}
              width={100}
              height={100}
            />
        </ImageContainer>
        <ButtonRs  href="https://www.linkedin.com/in/gabriel-figueroa-42776b262/"><h1>Linkedin</h1></ButtonRs>
            
          
      </DivRS >
    
       
        
        </DivRRSS>
       
        <DivColumn>
        <H1Center>Mis proyectos</H1Center> 
         <DivRow>
       

          <Button style={{margin: '0 10px'}} onClick={() => setContenidoProyectos(locc)} variant="contained">LoC</Button>
          <Button style={{margin: '0 10px'}} onClick={() => setContenidoProyectos(pokedex)} variant="contained">Pokedex </Button>
          <Button  style={{margin: '0 10px'}} onClick={() => setContenidoProyectos(openair)} variant="contained">OpenAir</Button>
         </DivRow>
          {contenidoProyectos}
        </DivColumn>
        <DivRow>
        <H1Center>Mis habilidades</H1Center> 
        </DivRow>
       
        <DivRRSS >
          <DivRS>
          <h1> Lenguajes y tecnologias</h1>
          <p>Tengo conocimiento alto: HTML, CSS, React, Next Js, JavaScript, .Net, Kotlin</p>
          <p>Tengo conocimiento medio: Java, Sql, Android nativo, Bootstraps</p>
          <p>Tengo conocimientos básicos: Nodejs, angular, Python y Php </p>
          </DivRS>
      <DivRS>
          <h1>contacto</h1>
        <a href=''>gmail</a>
      </DivRS>       
        </DivRRSS>

        <footer>
           <p>Este es el pie de página</p>
        </footer>
        
      
      

    </>
  )
}
